### ISSUE TITLE
empty service file created

### ISSUE THREAD

**Issue by Zaoliang** [tjfontaine/airprint-generate#30]
I got an empty service file 'AirPrint-hplaserjet100colormfpm175a.service' created:

--

@linux:~/Downloads/airprint-generate> ./airprint-generate.py -v
hplaserjet100colormfpm175a Losing support for: text/css,image/x-photocd,image/x-bitmap,image/pwg-raster,application/vnd.cups-raw,application/vnd.cups-postscript,application/vnd.cups-pdf-banner,application/vnd.hp lasercups-pdf
Traceback (most recent call last):
  File "./airprint-generate.py", line 279, in <module>
    apg.generate()
  File "./airprint-generate.py", line 226, in generate
    tree.write(f, pretty_print=True, xml_declaration=True, encoding="UTF-8")
  File "src/lxml/etree.pyx", line 2057, in lxml.etree._ElementTree.write
  File "src/lxml/serializer.pxi", line 758, in lxml.etree._tofilelike
  File "src/lxml/etree.pyx", line 318, in lxml.etree._ExceptionContext._raise_if_stored
  File "src/lxml/serializer.pxi", line 682, in lxml.etree._FilelikeWriter.write
TypeError: write() argument must be str, not bytes

--
My OS:  openSUSE Tumbleweed
Shared printer connected to printer server:  HP Laserjet 100 Color MFP M175a

any idea about this TypeError? Thanks!

**Comment by tmulzer** [comment]
Same with a kyocera printer and Arch Linux (Manjaro KDE).

**Comment by tmulzer** [comment]
PullRequest #31 is the solution.
