### ISSUE TITLE
ImportError: No module named cups 

### ISSUE THREAD

**Issue by MarcelloNicoletti** [tjfontaine/airprint-generate#9]
<code>import cups, os, optparse, re, urlparse
ImportError: No module named cups </code>
 I get this when I run this. I am running a RPi and it may be an issue with how the RPi package unpacked.

**Comment by branx86** [comment]
I have CentOs 8 and have "yum install system-config-printer-libs" installed but still gives ImportError: No module named cups, Is their other depends I'm missing

**Comment by branx86** [comment]
Well figured out the above problem by Doing in CentOs 8 " pip2 install cups" and " pip3 install cups" now I have : File "./airprint-generate.py", line 261, in
cups.setPasswordCB(getpass)
AttributeError: module 'cups' has no attribute 'setPasswordCB'

**Comment by YahBoiiJose** [comment]
> sudo apt-get install python-cups

I ran the apt-get command but it says "unable to locate package".
Im running linux mint 20
this worked before on linux mint 19

**Comment by YahBoiiJose** [comment]
> > sudo apt-get install python-cups
> 
> I ran the apt-get command but it says "unable to locate package".
> Im running linux mint 20
> this worked before on linux mint 19

nvm, i solved it. i just need to hunt down for the deb online since its there's no ubuntu 20.04 version available.

**Comment by josh64x2** [comment]
> Well figured out the above problem by Doing in CentOs 8 " pip2 install cups" and " pip3 install cups" now I have : File "./airprint-generate.py", line 261, in
> cups.setPasswordCB(getpass)
> AttributeError: module 'cups' has no attribute 'setPasswordCB'

@branx86 the package name in `pip` is actually `pycups` and not `cups`.

**Comment by Gill-Bates** [comment]
Nothing helped! Same issue with Debian Buster 10

**Comment by Gill-Bates** [comment]
`apt install python3-cups` has solved my issue under Debian 10 Buster

**Comment by abdros** [comment]
I am running Centos 7.9.2009. I have also come to the 'setPasswordCB' error.
I have installed:

> python34-cups-1.9.74-4.el7.x86_64
> python36-cups-1.9.74-4.el7.x86_64
> python-cups-1.9.63-6.el7.x86_64

Anyone has had any luck?
Thanks

**Comment by ersingencturk** [comment]
because the stupid python language has no dependency check or whatsoever. just random bunch of libraries everywhere not compatible with each other or version... update 2021 : the project was updated to python3 so you need to use python3 , second install cups package.. it's not called cups but pycups.. so use pip3 install pycups    ... both stupid import cups library has 2 meanings with 2 packages.. !

**Comment by DXorSX** [comment]
ensure you have only pycups installed. 
`pip3 uninstall cups`
`pip3 install pycups`

**Comment by WanderingApps** [comment]
It does not appear like the cups-pdf or python-cups dependencies are presently available

**Comment by mschindl** [comment]
I have the same issue, but after the first tips the error message changed.
Any idea how to get it running?

`# cat /etc/redhat-release 
Red Hat Enterprise Linux release 9.2 (Plow)`

`# python --version
Python 3.9.16`

`# pip3 list | grep cups
pycups               2.0.1`

`# sudo ./airprint-generate.py -d /etc/avahi/services/
Traceback (most recent call last):
  File "/root/./airprint-generate.py", line 279, in <module>
    apg.generate()
  File "/root/./airprint-generate.py", line 226, in generate
    tree.write(f, pretty_print=True, xml_declaration=True, encoding="UTF-8")
  File "src/lxml/etree.pyx", line 2057, in lxml.etree._ElementTree.write
  File "src/lxml/serializer.pxi", line 757, in lxml.etree._tofilelike
  File "src/lxml/etree.pyx", line 318, in lxml.etree._ExceptionContext._raise_if_stored
  File "src/lxml/serializer.pxi", line 681, in lxml.etree._FilelikeWriter.write
TypeError: write() argument must be str, not bytes`

---

Otherwise I tried the containerised method, but no file will be created:

`# podman run --rm -it -v $(pwd):/tmp airprint-generate -H 10.1.1.250 -d /root/`
I replaced the directory to root, because permission restriction in tmp.

**Comment by mschindl** [comment]
Any idea how to fix it?

**Comment by metzenseifner** [comment]
I would recommend ignoring package managers like apt-get and yum. Just use those to install Python 3 unless you want to compile it yourself.

Then do:

```
python -m env py3
source ./py3/bin/activate
echo $(which python) $(which pip) # Ensure it is the one you just created
pip install pycups # (THIS IS A TRAP! You want the package called pycups and mentioned above)
python airprint-generate.py
```

Which person thought it was a good idea to name the module "cups" and the package "pycups", while there is also a package called "cups" referring to something else? I ran into https://github.com/tjfontaine/airprint-generate/issues/9#issuecomment-570634614 and solved it by reading https://github.com/tjfontaine/airprint-generate/issues/9#issuecomment-719170249. Thanks everybody.

**Comment by ersingencturk** [comment]
> I would recommend ignoring package managers like apt-get and yum. Just use those to install Python 3 unless you want to compile it yourself.
> 
> Then do:
> 
> ```
> python -m env py3
> source ./py3/bin/activate
> echo $(which python) $(which pip) # Ensure it is the one you just created
> pip install pycups # (THIS IS A TRAP! You want the package called pycups and mentioned above)
> python airprint-generate.py
> ```
> 
> Which person thought it was a good idea to name the module "cups" and the package "pycups", while there is also a package called "cups" referring to something else? I ran into [#9 (comment)](https://github.com/tjfontaine/airprint-generate/issues/9#issuecomment-570634614) and solved it by reading [#9 (comment)](https://github.com/tjfontaine/airprint-generate/issues/9#issuecomment-719170249). Thanks everybody.

btw, in 2024 you don't need this repository for cups airprint anymore. when you share a printer a cups printer it is airprint ready automatically

**Comment by cshilton** [comment]
If for some reason you still need this script to generate an avahi service description for your printer and you are running into this problem, I solved it as follows on Rocky Linux 9.4:

```
$ ## Install OS requirements with the os package manager.
$ sudo dnf install python gcc python-devel cups-devel 
$ ## Create a place to work
$ mkdir tmphome && cd tmphome
$ ## Create a temporary place to work
$ git fetch <this repository>
$ ## Create a python environment for the pycups package note well that pycups needs gcc and
$ ## a couple of devel packages. 
$ python3 -m venv venv
$ . venv/bin/activate
$ pip install --upgrade pip
$ pip install pycups
$ python airprint-generate.py ...
```

This worked for me. All of the above got me to the point where I knew I needed to install pycups into a venv but it wouldn't build/install with just `pip install pycups`. Reading the [pycups documentation - https://github.com/OpenPrinting/pycups/blob/master/README](https://github.com/OpenPrinting/pycups/blob/master/README) got me the rest of the way.

**Comment by porteusconf** [comment]
Try the active fork https://github.com/Ljzd-PRO/airprint-generate which seems to create service xml files for me on debian-trixier. Have 2 virtual printers: boomaga and PDF (cups-pdf). I'll update here if airprinting itself seems to work or not ;-)

``` shell
$ sudo ./airprint-generate.py -d . -v
Boomaga Losing support for: text/css,image/x-photocd,image/x-bitmap,image/pwg-raster,application/vnd.cups-raw,application/vnd.cups-postscript,application/vnd.cups-pdf-banner,application/vnd.cups-pdf
Created: ./AirPrint-Boomaga.service
PDF Losing support for: text/css,image/x-photocd,image/x-bitmap,image/pwg-raster,application/vnd.cups-raw,application/vnd.cups-postscript,application/vnd.cups-pdf-banner,application/vnd.cups-pdf
Created: ./AirPrint-PDF.service, 

$ ls -l airprint-generate.py 
-rwxrwxr-x 1 student student 10539 Sep  3 20:45 airprint-generate.py

$ cat AirPrint-PDF.service 
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
  <name replace-wildcards="yes">AirPrint PDF @ %h</name>
  <service>
    <type>_ipp._tcp</type>
    <subtype>_universal._sub._ipp._tcp</subtype>
    <port>631</port>
    <txt-record>txtvers=1</txt-record>
    <txt-record>qtotal=1</txt-record>
    <txt-record>Transparent=T</txt-record>
    <txt-record>URF=DM3</txt-record>
    <txt-record>rp=printers/PDF</txt-record>
    <txt-record>note=PDF</txt-record>
    <txt-record>product=(GPL Ghostscript)</txt-record>
    <txt-record>printer-state=3</txt-record>
    <txt-record>printer-type=0x80f04c</txt-record>
    <txt-record>Color=T</txt-record>
    <txt-record>pdl=application/octet-stream,application/pdf,application/postscript,application/vnd.cups-raster,image/gif,image/jpeg,image/png,image/tiff,image/urf,text/html,text/plain,application/vnd.adobe-reader-postscript,application/vnd.cups-command</txt-record>
  </service>
</service-group>

```
I'll try to submit an issue to add link to active fork to the Readme,  With no pulls since 2020 original repo seems abandoned.
